import "./infoPages.css";
import { useEffect, useRef } from "react";

const KnowMorePage = (props: any) => {
  const knowMoreElement = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (knowMoreElement.current) {
      knowMoreElement.current.scrollTo({ top: 0 });
    }
  }, [props.activePage === "know-more"]);
  return (
    <div
      className={
        props.activePage === "know-more"
          ? "know-more_window"
          : "know-more_window know-more_hide"
      }
    >
      <div
        ref={knowMoreElement}
        className="know-more_content"
      >
        {props.language === "cz" && (
          <div>
            <p>
              Stoupání hladiny moří je jedním z důsledků globální klimatické
              změny, která je pravděpodobně zapříčiněna skleníkovým efektem.
              Tento přirozený jev je zesilován vlivem znečištění vznikajícího
              převážně lidskými aktivitami. Dochází proto k oteplování Země,
              tání ledovců a zvyšování hladiny světového oceánu.
            </p>
            <p>
              Měření výšky hladiny světového oceánu se do roku 1993 provádělo
              pomocí vodočtů umístěných převážně v přístavech. V současné době
              se měří pomocí satelitů, které jsou mnohem přesnější.
            </p>
            <p>
              Existuje řada vědeckých výpočtů, které se snaží předpovědět průběh
              stoupání hladiny moří. Do roku 2100 se odhady pohybují mezi
              0,3-1,1 m, do roku 2500 potom mezi 1,8-5,5 m. Závisí zejména na
              emisích skleníkových plynů a znečištění atmosféry.
            </p>
            <p>
              Jeden z vědeckých výpočtů říká, že kdyby se hladina moří zvedla o
              5 m, zmenšila by se rozloha pevniny o 5,5 milionů km2 (to je
              rozloha 70krát větší než rozloha České republiky). Nový domov by
              muselo hledat 670 milionů lidí (tedy 2krát více lidí, něž žije ve
              Spojených státech amerických, nebo 64krát více lidí, než žije v
              České republice).
            </p>
          </div>
        )}
        {props.language === "en" && (
          <div>
            <p>
              Rising sea levels is one of the consequences of global climate
              change, which is probably caused by the greenhouse effect. This
              natural phenomenon is amplified due to pollution that is mainly
              generated by human activities. As a result, the Earth is warming,
              glaciers are melting and the global sea level is rising. Until
              1993, measurements of the global sea level were made using gauges
              that were located mainly in ports. Today, measurements are taken
              by satellites that are much more accurate.
            </p>
            <p>
              There are a number of scientific calculations aiming to forecast
              the trends in the rise of sea levels. Estimates range from 0.3 to
              1.1 m for 2100 and from 1.8 to 5.5 m for 2500. This mainly depends
              on greenhouse gas emissions and air pollution. One scientific
              calculation says that if the sea level were to rise by 5 m, the
              area of land would decrease by 5.5 million km2 (70 times the size
              of the Czech Republic). 670 million people would have to seek new
              homes (twice the population of the USA, or 64 times the population
              of the Czech Republic).
            </p>
          </div>
        )}
        {props.language === "de" && (
          <div>
            <p>
              Der Anstieg des Meeresspiegels ist eine der Folgen des globalen
              Klimawandels, der wahrscheinlich durch den Treibhauseffekt
              verursacht wird. Diese natürliche Erscheinung wird durch den
              Einfluss der Verunreinigung verstärkt, die überwiegend durch
              menschliche Aktivitäten entsteht. Deshalb kommt es zur Erwärmung
              der Erde, zum Schmelzen der Eisberge und zum Anstieg des Spiegels
              der Weltmeere. Das Messen der Höhe des Weltmeerspiegels erfolgte
              bis 1993 mit Hilfe von Wasserstandsanzeigern, die überwiegend in
              Häfen untergebracht waren. Derzeit misst man mit Hilfe von
              Satelliten, die viel genauer sind.
            </p>
            <p>
              Es gibt eine Reihe wissenschaftlicher Berechnungen, die versuchen,
              den Verlauf des Anstiegs des Meeresspiegels vorherzusagen. Bis zum
              Jahr 2100 bewegen sich die Schätzungen zwischen 0,3 - 1,1 m, bis
              zum Jahr 2500 dann zwischen 1,8 - 5,5 m. Dies hängt insbesondere
              von den Treibhausgasemissionen und der Verschmutzung der
              Atmosphäre ab. Eine der wissenschaftlichen Berechnungen besagt,
              dass wenn der Meeresspiegel um 5 m ansteigen würde, sich die
              Fläche des Festlands um 5,5 Millionen km² verringern würde (dies
              ist eine Fläche 70mal größer als die Fläche der Tschechischen
              Republik). Eine neue Heimat müssten sich 670 Millionen Menschen
              suchen (also 2mal mehr Menschen, als in den Vereinigten Staaten
              von Amerika leben, oder 64mal mehr Menschen, als in der
              Tschechischen Republik leben).
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default KnowMorePage;
